name: Build and deploy to Nuget

on:
  push:
    branches:
      - dev
    tags:
      - "*"

jobs: 

  nuget:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true         
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"         

      - name: build
        run: dotnet pack ProtoActor.sln -c Release -o nuget -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
      - name: push
        run: dotnet nuget push nuget/**/*.nupkg --api-key ${{secrets.GITHUB_TOKEN}} --source --source "https://nuget.pkg.github.com/asynkron/protoactor-dotnet/index.json" --skip-duplicate        
